AllCops:
  NewCops: enable
require:
  - rubocop-rails
  - rubocop-rspec
Lint/MissingSuper:
  Enabled: false
Style/Documentation:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
